---
- hosts: ansible_Name_worker
  tasks:
      - name: "Installing Apache"
        apt:
           name: apache2
           update_cache: true
           state: latest

     - name: "Creating Document Root"
       file:
          path: /home/ubuntu/app/
          state: directory 

      - name: "Configure Web Page"
        template:
           src: index.html.j2
           dest: /home/ubuntu/app/index.html

      - name: "Start apache Servie"
        service:
           name: "apache2"
           state: started
           enabled: true


